# Generated by Django 5.2.1 on 2025-05-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_alter_fxohlc_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('baseCurrency', models.CharField(max_length=10)),
                ('quoteCurrency', models.CharField(max_length=10)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('date', models.DateTimeField()),
                ('tradesDone', models.FloatField()),
                ('volume', models.FloatField()),
                ('volumeNotional', models.FloatField()),
            ],
        ),
    ]
